# Generated by Django 5.1 on 2024-11-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='pregunta',
            field=models.ManyToManyField(to='art_app.pregunta'),
        ),
    ]
