# Generated by Django 5.1.3 on 2024-11-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0002_art_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='art_fecha',
            field=models.DateField(null=True),
        ),
    ]
