# Generated by Django 5.1 on 2024-11-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0003_art_art_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='art_fecha',
            field=models.DateField(),
        ),
    ]
