# Generated by Django 5.1 on 2024-11-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0005_respuestariesgo'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='art_Supervisor',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actividad',
            name='act_medida_control',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='act_riesgo',
            field=models.CharField(max_length=300),
        ),
    ]
