# Generated by Django 5.1 on 2024-11-20 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0006_art_art_supervisor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='pregunta',
        ),
        migrations.CreateModel(
            name='ArtPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.BooleanField()),
                ('id_art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art_app.art')),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art_app.pregunta')),
            ],
        ),
    ]
