# Generated by Django 5.1 on 2024-11-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0007_remove_art_pregunta_artpregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='pregunta',
            field=models.ManyToManyField(through='art_app.ArtPregunta', to='art_app.pregunta'),
        ),
    ]
