# Generated by Django 5.1 on 2024-11-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0009_rename_respuesta_artpregunta_respuestatrans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art',
            old_name='art_Supervisor',
            new_name='art_supervisor',
        ),
        migrations.AddField(
            model_name='art',
            name='art_estado',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
