# Generated by Django 5.1 on 2024-12-13 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0010_rename_art_supervisor_art_art_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='art_comunicAccions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='art',
            name='art_contextTrabSim',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='art',
            name='art_coordLider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='art',
            name='art_verfControles',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='respuestariesgo',
            name='art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_riesgo', to='art_app.art'),
        ),
        migrations.AlterField(
            model_name='respuestariesgo',
            name='respuesta',
            field=models.BooleanField(default=False),
        ),
    ]
