# Generated by Django 5.1 on 2024-12-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0011_art_art_comunicaccions_art_art_contexttrabsim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='art_estado_Super',
            field=models.BooleanField(default=False),
        ),
    ]
