# Generated by Django 5.1 on 2024-12-11 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0011_art_art_comunicaccions_art_art_contexttrabsim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestariesgo',
            name='art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_riesgo', to='art_app.art'),
        ),
    ]
