# Generated by Django 5.1 on 2024-11-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('emp_rut', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('emp_nombre', models.CharField(max_length=100)),
                ('emp_correo', models.CharField(max_length=100)),
                ('emp_telefono', models.CharField(max_length=9)),
                ('emp_direccion', models.CharField(max_length=100)),
                ('emp_cargo', models.CharField(max_length=100)),
                ('emp_contraseña', models.CharField(max_length=32)),
                ('emp_especialidad', models.CharField(max_length=100)),
            ],
        ),
    ]
