# Generated by Django 5.1 on 2024-11-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='emp_actividad',
            field=models.CharField(default='sin actividad', max_length=100),
            preserve_default=False,
        ),
    ]
