# Generated by Django 5.1 on 2024-12-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_app', '0002_empleado_emp_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='emp_rut',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
