# Generated by Django 5.1 on 2024-12-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_app', '0003_alter_empleado_emp_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='emp_presente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empleado',
            name='emp_supervisorAcargo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='emp_turno',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
